### ISSUE TITLE
Standalone log exporter needs UI enhancements: resource location selection and date filter

### ISSUE THREAD

**Issue by AliAhmedNada** [neatnik/watson-assistant-utilities#1]
Hello 

there is an issue for standalone exporter , whenever i submit key username and password , workspace, it give me access denied 
![image](https://user-images.githubusercontent.com/17008257/54857113-bbf83e80-4d0e-11e9-90fb-f6c50950e921.png)

i am using the key exist in the workspace : username : apikey 
password : xxxxxxxxxxxxxxxxxxxxxxxx

Regards
Ali Ahmed Nada

**Comment by newbold** [comment]
Hi Ali. I suspect the issue might be related to the script being hard-coded to use the Dallas service endpoint. Do you know which location hosts your Watson Assistant resource? If so, you can [find the correct service endpoint URL here](https://cloud.ibm.com/apidocs/assistant#service-endpoint) and then edit line 74 of the script to reflect the correct URL for your resource location.

For instance, if your resource is hosted in Frankfurt, you'd change line 74 from:

`$url = 'https://gateway.watsonplatform.net/assistant/api'.$method;`

to

`$url = 'https://gateway-fra.watsonplatform.net/assistant/api'.$method;`

Let me know if that fixes the issue. If it does, then I can add a Location selection to the form to make things easier going forward. I just want to confirm that this is in fact the source of the authentication issue, though. Thanks!

**Comment by AliAhmedNada** [comment]
I believe this is the Problem , many Thanks 
also i have another question what is the limit Conversations could be extracted ?!

**Comment by newbold** [comment]
It ranges from 7 to 90 days depending on the type of plan you're using. Check out the Log Limits section on [this page](https://cloud.ibm.com/docs/services/assistant?topic=assistant-logs#logs) for details. 😀

Though looking at the script now, it seems I may have left some hard-coded defaults in place that limit the scope of what it will retrieve via the API. Check out lines 132 and 133, where `$start` and `$end` are set. The default behavior goes back only 3 days, but you can change that to anything you'd like. This is something else that I need to add to the form (I think I had intended to, but clearly didn't get around to it). Keep an eye out for an updated version of the script to be shared soon.

**Comment by AliAhmedNada** [comment]
@newbold  i am having a problem with the amount lets say i have 1 Million Chat conversation within 1 month , is the log api is ready to have such a request ?!

**Comment by newbold** [comment]
In theory it should be OK, but I've never tested it against workspace with a significant amount of activity. The script uses the API's pagination/cursor feature, which offers expanded rate limiting ([120 requests per minute](https://cloud.ibm.com/apidocs/assistant#list-log-events-in-a-workspace)). On a really large workspace it's possible that rate limiting could become an issue, and the script doesn't currently account for that. If you run into difficulty pulling all of your data from a large workspace, I'd be glad to try to adjust the script as needed.

**Comment by AliAhmedNada** [comment]
well unfortunately i do have this problem  :)

**Comment by newbold** [comment]
The script has been updated, and the new version can be found [here](https://github.com/neatnik/watson-assistant-utilities/blob/master/log-csv-exporter-standalone.php).

Here's what's changed:

- The form now lets you select the service endpoint, which corresponds to the location of your Watson Assistant instance 
- The form also now allows you to specify your date range for the export; you can enter text like "five hours ago" or "6 days ago" as well as specific dates (and even times), like "2019-03-01 03:15:00"
- The export is no longer dumped into the browser as a download; instead, there is now a real-time view of the API execution, and when this is finished a button will appear to download the saved export

<img width="427" alt="Screen Shot 2019-03-24 at 11 08 45 PM" src="https://user-images.githubusercontent.com/986721/54893506-85e0c900-4e8c-11e9-9ce1-dd109b769e80.png">

Note that the real-time API execution view might not work in all browsers (for instance, testing on a Mac, it did not work for me in Safari but it did work in Chrome). You'll know it's working if you see information about the API calls being displayed along with a note about the amount of time that has elapsed.

The timer information might be useful in further troubleshooting, especially with larger workspaces with more data. It's possible that the script will require more time to execute than your PHP settings are configured for. If the script stops, you should make note of the elapsed time and then check your PHP's [max_execution_time](https://www.php.net/manual/en/info.configuration.php#ini.max-execution-time) settings.

I hope you find this useful, and let me know how it works for you.

**Comment by AliAhmedNada** [comment]
@newbold  Great work , much appreciated :)
